### ISSUE TITLE
Setup a system for student backups

### ISSUE THREAD

**Issue by yuvipanda** [data-8/infrastructure#13]
If the PVCs for student pods get accidentally deleted, we lose all student data. This is bad.

There's currently a hacky backup script, running:

```bash
gcloud compute disks list | grep gke-prod-49ca6b0d-dyna-pvc | awk '{ print $1; }'  | xargs -L1 gcloud compute disks snapshot
```

This needs to be better.

**Comment by yuvipanda** [comment]
I just ran it again, because why not

**Comment by yuvipanda** [comment]
A decent halfway solution would be a script that:

1. Looks for all persitent volume claims in a namespace
2. Finds the GCE Persistent Disk attached to them
3. If there's no recent snapshot, then make a snapshot!

We can run this daily.  We should also have a separate script that purges old snapshots - we shouldn't keep more than 2 maybe.

**Comment by yuvipanda** [comment]
The structure of the script would be pretty similar to the autoscaling script, but should be written as a separate and independent one. Although if there is good code sharing opportunities, we should just make them into the same python package.

**Comment by SaladRaider** [comment]
@yuvipanda @jiefugong It seems like this is done. Should we close this?
