### ISSUE TITLE
Make student pod memory limit be 1G, not 2G

### ISSUE THREAD

**Issue by yuvipanda** [data-8/infrastructure#16]
Saves cost, and students aren't legitimately using more than 1G most of the time.

**Comment by yuvipanda** [comment]
I've now set datahub-dev to 1G, and seems ok. I'll move prod over tomorrow.

**Comment by yuvipanda** [comment]
Done for prod, and everything seems ok! 

@ryanlovett should we do this for prob140 and stat28 too?

**Comment by ryanlovett** [comment]
Yes, will start with dev.

**Comment by yuvipanda** [comment]
Was done
