### ISSUE TITLE
Some nodes are unpopulated with the latest user image

### ISSUE THREAD

**Issue by SaladRaider** [data-8/infrastructure#25]
One instance where this happened was with the user `lehooshyar` in the data8 class. This user appeared to have too many redirects. However, the user's node was trying to pull in the current user image because it did not exist already on the node.

**Comment by yuvipanda** [comment]
@ryanlovett ran into this today too. Perhaps we can increase the amount of time between the autoscaler running and populate.bash running?

**Comment by yuvipanda** [comment]
Going to close this since we're no longer on GKE
