### ISSUE TITLE
Data8 Bridge Course summer infrastructure setup!

### ISSUE THREAD

**Issue by yuvipanda** [data-8/infrastructure#29]
Checklist to making it happen!

- [x] Make sure we have enough Azure money for it to last ( @ryanlovett )
- [x] Setup Yuvi with authenticaton on Azure properly ( @ryanlovett )
- [x] Figure out where the db for JupyterHub should live
- [x] Setup an NFS server on Azure for the class ( @ryanlovett )
- [x] Figure out how to auto mount NFS on all the k8s nodes (with a daemonset maybe?)  ( @yuvipanda)
- [ ] Make sure that hostPath works fine with JupyterHub for students
- [ ] Setup prometheus on this cluster with a prometheus operator
- [ ] Setup Grafana with a helm chart
- [ ] Do a simple stress test to make sure this can handle students

We want to get all of this done by June 7 IMO.

**Comment by yuvipanda** [comment]
For mounting NFS, I *think* just setting up a PV + PVC manually, and then using [subpath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) would actually be enough!

We can then have one NFS share (represented by one PV) per hub, and just have PVCs bind to that with ReadWriteMany. This will let us shard NFS servers by hub if necessary!

**Comment by henryem** [comment]
Thanks so much for putting this together.

**Comment by yuvipanda** [comment]
@ryanlovett did we figure out the money situation?

**Comment by ryanlovett** [comment]
Yes, we're going to receive an advance on the grant. It will probably displace the remaining research grant. I'll work with MS on the transfer next week.

**Comment by henryem** [comment]
Hey guys, any update on this?  Would be good to have a dry run soon.

One question: how hard would it be to store the materials at a repo other than data-8/data8assets?  I'm thinking it might be best to use a separate one for this course.

**Comment by ryanlovett** [comment]
Hi Henry,

Yuvi and I plan to bring up the hub tomorrow afternoon.

It is trivial to specify an alternative repo within data-8; some of the
other courses do that. We can create a data8r-assets repo or some such for
that purpose where you'd literally replace data8assets with the new repo
name. Last I checked it wasn't possible to use a repo outside of data-8,
unless it was as an http URL and not a git path.


Ryan

**Comment by henryem** [comment]
Great, thanks.  I'm okay putting the repo in data-8.  I can create it if
there's no special setup involved.

FYI, I'll be using a branch (or maybe a fork) of data8's assignments repo
for the assignment sources.

-Henry

**Comment by ryanlovett** [comment]
We (mostly Yuvi) did the bulk of the work setting up your hub this afternoon. We should be finished by tomorrow. Yuvi, I'll do the OAuth config tonight.

I think we'll honor the convention and use data8r.datahub.berkeley.edu. 😐 

By tomorrow you should be able to access the hub's IP; the hostname will take a couple of days to get processed.

**Comment by henryem** [comment]
As discussed earlier, I would have preferred data8r.datahub.data.dat, but
it'll have to do.

(Thanks!)

-Henry

**Comment by ryanlovett** [comment]
We have the hub setup, temporarily with a non berkeley.edu hostname which I'll email shortly. We have to wait for campus DNS for the real hostname.

The singleuser image is at https://github.com/data-8/singleuser-data8 so if you need changes, please file PRs on that repo.

We still need to add nbpuller.

**Comment by yuvipanda** [comment]
This is done, so closing it.
