### ISSUE TITLE
Figure out how to manage subscriptions

### ISSUE THREAD

**Issue by yuvipanda** [data-8/infrastructure#31]
Questions about Azure subscriptions!

1. Can you add money to a subscription from a sponsorship?
2. Are subscriptions ACL'd? Can I give someone access to one subscription and not another?
3. Can we get early notification when a subscription is running low?

**Comment by ryanlovett** [comment]
1. We have done this before, but new subscriptions not longer show up in the Education portal. I've an open ticket with MS support. Azure staff aren't familiar with the Education portal so they have to source someone in another business unit. Still, the front line support said that we must go through them.
2. Yes, subscriptions have their own account management. This can be modified in the edu portal or in the azure portal.
3. There is an API for determining this as well as https://docs.microsoft.com/en-us/azure/billing/billing-set-up-alerts. I've done the latter for subscription data8r-17s as a test.
