### ISSUE TITLE
Data 8X unique usernames

### ISSUE THREAD

**Issue by davidwagner** [data-8/infrastructure#37]
For Data 8X, we might want to think about how to map email addresses to usernames: if there are two students bob@gmail.com and bob@yahoo.com, are they going to conflict with each other?  (because both email addresses map to the local username bob)

**Comment by yuvipanda** [comment]
Depends on what authenticator we use! I suppose we'll be using an edx specific authenticator that only lets people with edx credentials log in?

Do you know anyone at edx we can talk to about this?

**Comment by ryanlovett** [comment]
https://github.com/edx/edx-oauth2-provider

I think a user of the edx instance (akin to a course admin?) would need to register the jupyterhub server there and generate the client id/secret. This is assuming the edx instance has installed the OAuth2 provider.
