### ISSUE TITLE
Replication Set unchanged after running deploy.bash

### ISSUE THREAD

**Issue by SaladRaider** [data-8/infrastructure#8]
There was an instant where a new user datahub image was built, all the nodes were populated with the new image, and the prod.yaml for data8 was edited to match the new image tag. After running deploy.bash, however, the hub did not restart. The hub still had the old user image tag. Deleting the hub and forcing it to restart resulted in the same old user image tag. After checking the Replication Set, the single user image was still referring to the old image. The deployment worked after manually changing the Replication Set spec via the Kube Dashboard. 

Before the manual change, doing a `helm get <prod release>` showed the correct new single user image tag, but that change was not reflected in the actual deployment.

**Comment by yuvipanda** [comment]
I haven't seen this happen since - things seem to be ok?
